
# Operasi Matematika & Numpy
Sebelum lanjut, harap:
1. Jika menggunakan jupyter, silahkan pilih "File" --> "Download" --> "Download .ipynb"
2. Jika menggunakan colab, silahkan pilih "File" --> "Save a copy in drive"

In [4]:
import numpy as np

### Pengenalan array

In [5]:
#1D array
a = np.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [6]:
#Slicing
a[:]

array([[1, 3, 0],
       [2, 4, 1],
       [3, 6, 7]])

In [7]:
#Slicing
a[:2]

array([[1, 3, 0],
       [2, 4, 1]])

In [8]:
#Slicing
a[2]

array([3, 6, 7])

In [9]:
#Slicing
a[1:]

array([[2, 4, 1],
       [3, 6, 7]])

In [10]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [[2 4 1]
 [3 6 7]]
a[:3] =  [[1 3 0]
 [2 4 1]
 [3 6 7]]


In [11]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Latihan-2 (2D array)

In [12]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', a.size )
print('dimensi array = ', a.ndim )
print('ukuran array = ', a.shape )

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [13]:
#Slicing
print('baris ke-2 = ', A[1])
print('entry ke-2 & 3 baris ke-2 = ', A[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', A[:2, 1])

baris ke-2 =  [4 5 6]
entry ke-2 & 3 baris ke-2 =  [5 6]
entry pertama & 2 kolom ke-2 =  [2 5]


### Latihan-3 (Slicing)

In [14]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


output jawaban:
baris ke-3 =  [7 8 9]

entry ke-1 & 2 baris ke-3 =  [7 8]

entry ke-2 & 3 kolom ke-3 =  [6 9]

### Operasi Matematika di Numpy

In [15]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [16]:
print('perkalian matriks = ')
print(np.matmul(A,A))

perkalian matriks = 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Bisa dilihat perbedaan perkalian antar entry dan perkalian matriks biasa?

In [17]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks C = ', np.linalg.det(C))

determinan matriks A =  -9.51619735392994e-16
determinan matriks C =  -216.00000000000006


In [18]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [19]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


In [20]:
print('vektor eigen matriks A = ', np.linalg.eig(A)[1])

vektor eigen matriks A =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [21]:
e_vec = np.linalg.eig(A)[1][:, 0] #Menagambil eigen vector pertama ([-0.23197, -0.52532209, -0.8186735  ])
e_val = np.linalg.eig(A)[0][0] #Mengambil eigen value pertama (1.61168440e+01)

In [22]:
print(np.matmul(A, e_vec)) #hasil A * eigen vector

[ -3.73863537  -8.46653421 -13.19443305]


In [23]:
print(e_val*e_vec) #hasil eigen value * eigen vector (Hasilnya sama)

[ -3.73863537  -8.46653421 -13.19443305]


### Latihan-4 (Operasi matriks)

In [24]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [30]:
#Ketik Kode disini
print("Hasil dari 2*A : ", 2*A)
print("Hasil dari 2+A : ", 2+A)
print("Hasil dari A+B : ", A+B)
print("Hasil dari Determinan A : ", np.linalg.det(A))

D = np.linalg.inv(B)
print("Invers dari B : ", D)
print("Transpose dari D : ", np.transpose(D))
print("Nilai eigen dan vektor eigen dari A : ",np.linalg.eig(A)[0],"dan",np.linalg.eig(A)[1])
print("Nilai eigen dan vektor eigen dari B : ",np.linalg.eig(B)[0],"dan",np.linalg.eig(B)[1])

Hasil dari 2*A :  [[ 2  4]
 [14 16]]
Hasil dari 2+A :  [[ 3  4]
 [ 9 10]]
Hasil dari A+B :  [[ 4  7]
 [ 8 14]]
Hasil dari Determinan A :  -6.0
Invers dari B :  [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]
Transpose dari D :  [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]
Nilai eigen dan vektor eigen dari A :  [-0.62347538  9.62347538] dan [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]
Nilai eigen dan vektor eigen dari B :  [1.8074176 7.1925824] dan [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [33]:
#Tunjukkan bedanya di kodingan di bawah ini
print("Perkalian entry B*D", B*D)
print("Perkalian matriks B dan D :", np.matmul(B,D))

Perkalian entry B*D [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
Perkalian matriks B dan D : [[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]


output jawaban: 

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308,  1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]]
